version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - gosec
    - misspell
    - revive
  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true
        - name: duplicated-imports
          severity: warning
        - name: exported
          arguments:
            - disableStutteringCheck
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/rollkit
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
